# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='ed_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='ing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Profile'),
        ),
    ]
