# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='time',
        ),
    ]
