# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['update_date']},
        ),
    ]
