# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
