# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20170208_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-update_date']},
        ),
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ('-date',)},
        ),
    ]
