# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20170208_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ('date',)},
        ),
    ]
