# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20170209_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', '草稿箱'), ('p', '已公共发布'), ('s', '私人文章')], default='p', max_length=1),
        ),
    ]
